version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing Composer dependencies..."
      - composer install --no-dev --optimize-autoloader
  pre_build:
    commands:
      - echo "Setting permissions..."
      - chmod -R 775 storage bootstrap/cache
      - echo "Caching Laravel configuration..."
      - php artisan config:cache || true
      - php artisan route:cache || true
      - php artisan view:cache || true
  build:
    commands:
      - echo "Zipping source code for deployment..."
      - zip -r ../laravel-app.zip . -x "*.git*" "tests/*"
artifacts:
  files:
    - ../laravel-app.zip
