version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing Composer dependencies...
      - curl -sS https://getcomposer.org/installer | php
      - php composer.phar install --no-dev --optimize-autoloader

  pre_build:
    commands:
      - echo "Generating Laravel config cache..."
      - php artisan config:cache
      - php artisan route:cache

artifacts:
  files:
    - '**/*'

