version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing dependencies..."
      - composer install --no-dev --optimize-autoloader

  pre_build:
    commands:
      - echo "Running Laravel pre-build tasks..."
      - php artisan config:cache
      - php artisan route:cache

  build:
    commands:
      - echo "Build phase - no action needed"

artifacts:
  files:
    - '**/*'
  discard-paths: no
