version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing Composer dependencies..."
      - composer install --no-dev --optimize-autoloader

  pre_build:
    commands:
      - echo "Caching Laravel config..."
      - php artisan config:cache
      - php artisan route:cache

  build:
    commands:
      - echo "Build phase completed"

artifacts:
  files:
    - '**/*'
  discard-paths: no

